<?php
/* * * * * * * * * * * * * * * * * * * *
 *  ██████╗ █████╗  ██████╗ ███████╗
 * ██╔════╝██╔══██╗██╔═══██╗██╔════╝
 * ██║     ███████║██║   ██║███████╗
 * ██║     ██╔══██║██║   ██║╚════██║
 * ╚██████╗██║  ██║╚██████╔╝███████║
 *  ╚═════╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝
 *
 * @author   : Daan van den Bergh
 * @url      : https://daan.dev/wordpress/caos/
 * @copyright: (c) 2021 Daan van den Bergh
 * @license  : GPL2v2 or later
 * * * * * * * * * * * * * * * * * * * */

$createConfig = apply_filters('caos_analytics_ga_create_config', array(
    'cookieName'    => 'caosLocalGa',
    /**
     * @since v4.2.3 cookieDomain used to be set using $_SERVER['SERVER_NAME']. However,
     *               since that superglobal relies heavily on server configuration, using
     *               a stripped home_url() is more user focussed and transparent.
     */
    'cookieDomain'  => parse_url(home_url())['host'],
    'cookieExpires' => CAOS_COOKIE_EXPIRY_SECONDS,
    'cookieFlags'   => 'samesite=none;secure'
));

$custom_attributes = apply_filters('caos_analytics_custom_attributes', '');
$tracking_id = \CAOS\Plugin::get(\CAOS\Admin\Settings::CAOS_BASIC_SETTING_TRACKING_ID);
$bounce_rate = \CAOS\Plugin::get(\CAOS\Admin\Settings::CAOS_BASIC_SETTING_ADJUSTED_BOUNCE_RATE);
?>
<script<?php echo $custom_attributes ? ' ' . $custom_attributes : ''; ?>>
    window.ga = window.ga || function() {
    (ga.q = ga.q || []).push(arguments);
    };
    ga.l = +new Date;

    <?php if (apply_filters('caos_analytics_use_local_storage', false)) : ?>
        if (window.localStorage) {
        ga('create', '<?= $tracking_id; ?>', <?= str_replace('"localStorage.getItem(\'GA_CLIENT_ID_HASHED\')"', 'localStorage.getItem(\'GA_CLIENT_ID_HASHED\')', json_encode($createConfig)); ?>);
        }
    <?php else : ?>
        ga('create', '<?= $tracking_id; ?>', <?= json_encode($createConfig); ?>);
    <?php endif; ?>

    <?php
    /**
     * Allow WP DEVs to easily modify CAOS' analytics.js configuration with a plugin.
     *
     * Example: add_filter('caos_analytics_before_send', 'your_filter_function_name');
     */
    ?>
    <?= implode("\n", apply_filters('caos_analytics_before_send', array(), $tracking_id)); ?>
    ga('send', '<?= apply_filters('caos_analytics_hit_type', 'pageview'); ?>');
    <?php
    /**
     * Allow WP DEVs to easily modify CAOS' analytics.js configuration with a plugin.
     *
     * Example: add_filter('caos_analytics_after_send', 'your_filter_function_name');
     */
    ?>
    <?= implode("\n", apply_filters('caos_analytics_after_send', array(), $tracking_id)); ?>
    <?php if ($bounce_rate) : ?>
        setTimeout("ga('send', 'event', 'Adjusted Bounce Rate', '<?= $bounce_rate . ' seconds'; ?>')", <?= $bounce_rate * 1000; ?>);
    <?php endif; ?>
    <?php if (\CAOS\Plugin::get(\CAOS\Admin\Settings::CAOS_EXT_SETTING_TRACK_AD_BLOCKERS)) : ?>
        var event = new Event('caos_track_ad_blockers');
        document.dispatchEvent(event);
    <?php endif; ?>
    </script>