<?php
/* * * * * * * * * * * * * * * * * * * *
     *  ██████╗ █████╗  ██████╗ ███████╗
     * ██╔════╝██╔══██╗██╔═══██╗██╔════╝
     * ██║     ███████║██║   ██║███████╗
     * ██║     ██╔══██║██║   ██║╚════██║
     * ╚██████╗██║  ██║╚██████╔╝███████║
 *  ╚═════╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝
 *
 * @author   : Daan van den Bergh
 * @url      : https://daan.dev/wordpress/caos/
 * @copyright: (c) 2021 Daan van den Bergh
 * @license  : GPL2v2 or later
 * * * * * * * * * * * * * * * * * * * */

/**
 * Allow WP DEVs to easily modify CAOS' Gtag.js configuration with a plugin.
 *
 * Example: add_filter('caos_gtag_config', 'your_filter_function_name', 10, 2);
 */
$tracking_id = \CAOS\Plugin::get(\CAOS\Admin\Settings::CAOS_BASIC_SETTING_TRACKING_ID);
$gtag_config       = apply_filters('caos_gtag_config', array(
    'cookie_prefix'  => 'CaosGtag',
    'cookie_domain'  => $_SERVER['SERVER_NAME'],
    'cookie_expires' => CAOS_COOKIE_EXPIRY_SECONDS,
    'cookie_flags'   => 'samesite=none;secure'
), $tracking_id);
$gtag_config       = apply_filters('caos_gtag_config_json', json_encode($gtag_config, JSON_UNESCAPED_SLASHES));
$custom_attributes = apply_filters('caos_gtag_custom_attributes', '');
$bounce_rate = \CAOS\Plugin::get(\CAOS\Admin\Settings::CAOS_BASIC_SETTING_ADJUSTED_BOUNCE_RATE);


?>
<script<?php echo $custom_attributes ? ' ' . $custom_attributes : ''; ?>>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
    dataLayer.push(arguments);
    }
    gtag('js', new Date());
    gtag('config', '<?= $tracking_id; ?>', <?= $gtag_config; ?>);
    <?=
    /**
     * Allow WP DEVs to easily modify CAOS' Gtag.js configuration with a plugin.
     *
     * Example: add_action('caos_gtag_additional_config', 'your_filter_function_name');
     */
    do_action('caos_gtag_additional_config');
    ?>
    <?php if ($bounce_rate) : ?>
        setTimeout("gtag('event', '<?= $bounce_rate . ' seconds'; ?>', {'event_category': 'Adjusted Bounce Rate'})", <?= $bounce_rate * 1000; ?>);
    <?php endif; ?>
    <?php if (\CAOS\Plugin::get(\CAOS\Admin\Settings::CAOS_EXT_SETTING_TRACK_AD_BLOCKERS)) : ?>
        var event = new Event('caos_track_ad_blockers');
        document.dispatchEvent(event);
    <?php endif; ?>
    </script>